### ISSUE TITLE
Use case for GGXF

### ISSUE THREAD

**Issue by RogerLott** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#1]
Item | Coordinate   Operation | Example   file format
-- | -- | --
1 | latitude/longitude   offsets | NTv2, NADCON   / NADCON5
2 | latitude/longitude/ellipsoid-height   offsets | NADCON5   (NGS)
3 | geocentric   Cartesian XYZ offsets | (IGN)
4 | easting/northing   offsets | OSTN   (OSGB)
5 | gravity-related   height offset | GTX,   LINZ, BEV, VERTCON
6 | geoid   models | numerous
7 | quasi-geoid   models | numerous
8 | hybrid   geoid (height correction) models | numerous
9 | hydroid   models | several
10 | deformation   model | GeoTIFF   (LINZ/Proj.7), NKG2016LU
11 | velocity   grid (N,E,Up) |  
12 | velocity   grid (E,N,Up) | NTv2   modified (NRCan)
  | **Coordinate list** |  
13 | geocentric   Cartesian XYZ + velocities | IERS   Sinex files
14 | geodetic   control list | various
15 | benchmark   list | various

In the table above, numerous file formats are mentioned or alluded to. For example, in items 1 and 2, NTv2 and NADCON files of latitude/longitude offsets utilise a different number of files with completely different formats to achieve the same end. For items 6 to 9, geoid models (using the term in a generic sense), end users sometimes feel that nearly every agency producing a model has their own proprietary format, and some agencies have different file formats within that one agency. Spreadsheets and csv files are sometimes used for data dissemination, in some cases without adequate explanation of the data content.
These problems make it very difficult to consume the data. This is summarised by Kelly et al in §1 of
https://github.com/Esri/ggxf/blob/master/IAGS-S-15-00075.pdf  

Were there to be a standard grid file format then:
•	Grid producers would not have to provide their own software for each data format.
•	Survey and GIS software vendors would need to read only one grid file format.
•	End users could use a new grid file as soon as it became available, without having to wait for their application vendor to produce a software upgrade.

**Comment by rouault** [comment]
Are the "Coordinate list" use cases part of the scope of GGXF ? List and regularly spaced grids are rather different objects

**Comment by ccrook** [comment]
The grid use cases above implemented in the current GGXF specification.  The non-grid use cases (eg lists) are outside the scope of GGXF.  Closing this issue.
