### ISSUE TITLE
GGXF Conventions: Uncertainty measure identifiers for Table C.7

### ISSUE THREAD

**Issue by kevinmkelly** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#14]
The following tables attempt to identify 1D, 2D and 3D uncertainty measures for GGXF Conventions in Table C.7. All entries in the tables below need not be used in Table C.7, only those the PT feels are most relevant. These accuracy measures come mainly from the navigation and positioning domain, so there may be others left out that may also be applicable. Note that the PT decided not to include covariance matrix, so it does not appear in the tables below. The "Uncertainty measure identifier" is only my suggestion, they can be changed if the PT prefers a different identifier.

### **One-dimensional** Accuracy Indicators

| Uncertainty measure name       |Uncertainty measure identifier     | Definition     |
| :------------- | :----------: | :----------- |
|  Standard error (1-sigma) | 1SE   |Standard deviation of the mean. 68% probability.    |
|  Standard error (2-sigma)| 2SE   |Twice the standard error. 95% probability.    |
|  Standard error (3-sigma)| 3SE   |Three times the standard error. 99% probability.    |
| Root mean square  | RMS |Standard deviation of residuals.  68% probability.|

a. Standard deviation is not strictly a measure of accuracy, but of precision. Standard error of the mean yields a confidence interval (CI), which more correctly expresses accuracy.

### **Two-dimensional** Accuracy Indicators

| Uncertainty measure name       |Uncertainty measure identifier     | Definition     |
| :------------- | :----------: | :----------- |
|  Distance root mean squared (1DRMS) | 1DRMS   | Square root of the trace of a two-dimensional covariance matrix. 66% probability.    |
|  Distance root mean squared (2DRMS) | 2DRMS   | Twice the 1DRMS. 97% probability.    |
|  Circular error probable (CEP) | CEP  | The radius of a circle, centered on the mean, whose boundary is expected to include the true value with 50% probability.   |
|  Circular error probable (2CEP) | 2CEP  | The radius of a circle, centered on the mean, whose boundary is expected to include the true value with 95% probability.   |
|  Standard confidence ellipse  | 1CEE  | An ellipse, centered on the mean, whose boundary is expected to include the true value with 39% probability.    |
|  95% confidence ellipse  | 2CEE  |An ellipse, centered on the mean, whose boundary is expected to include the true value with 95% probability.    |

### **Three-dimensional** Accuracy Indicators

| Uncertainty measure name       |Uncertainty measure identifier     | Definition     |
| :------------- | :----------: | :----------- |
|  Spherical error probable (SEP) | SEP  | The radius of a sphere, centered on the mean, whose boundary is expected to include the true value with 50% probability.  |
|  Standard confidence ellipsoid  | 1CED  |An ellipsoid, centered on the mean, whose boundary is expected to include the true value with 20% probability.   |
|  95% confidence ellipsoid  | 2CED  |An ellipsoid, centered on the mean, whose boundary is expected to include the true value with 95% probability.    |

### **References**
Leenhouts, P. P. (1985). On the computation of bi-normal radial error. NAVIGATION, Journal of the Institute of Navigation, 32(1), 16-28.

Langley, R. B. (1991). The mathematics of GPS. GPS World, 2(7), 45-50.

**Comment by ccrook** [comment]
@kevinmkelly This is a great list. We will need to support this with some keywords for the parameters required for each variant.  Obviously from a navigation background there is better support for 2d errors. 

I wonder if there might be a desire in GGXF to distinguish between 95% confidence limit and 2 standard error.  Given the uncertainty of the uncertainty this is not a practical difference, but I could imagine a desire to represent it as confidence rather than a multiple of SE  or vice versa.   But that can be covered by tidying up as per your initial comment.  

From the point of view of deformation modelling we will potentially add combinations of horizontal and vertical uncertainty.  They could be separate fields. That would preclude 3 dimensional ellipsoidal uncertainty which don't have one axis aligned with the vertical axis.  That may not be something we expect to encounter in the near future.

**Comment by RogerLott** [comment]
With some minor edits (e.g. id "CEP" changed to "1CEP" for consistency with other ids) these have been added to table C.7 in GGXF draft v0.6.

**Comment by RogerLott** [comment]
PT meeting 2022-01-30 agreed to use uncertainty measure identifier and include name in definition.
