### ISSUE TITLE
Is ZARR format an option for GGXF

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#19]
One of the technology savvy people at LINZ (Jeremy Palmer) has suggested it might be worth also considering the ZARR format as a carrier for GGXF.  This is a much younger format than NetCDF (if not NetCDF4) and provides a set of capabilities very compatible with GGXF requirements (eg groups, subgroups, arbitrary dimension arrays).  There are at least C++ and Python implementations. 

* OGC community standard - request for comment: https://www.ogc.org/standards/requests/235
* GDAL driver - https://gdal.org/drivers/raster/zarr.html#raster-zarr
* Python API documentation - https://zarr.readthedocs.io/en/stable/

The GDAL driver includes a geospatial referencing implementation, though that is not the same as the GGXF affine transformation approach  So as with NetCDF we would be overlaying the nested grid structure, spatial referencing, and GGXF metadata elements on top of the carrier specification.

The format comprises JSON formatted metadata elements with binary formatted grid data identified by path like string identifiers and compiled into a single file. 

Possible advantages of ZARR:
* JSON formatted metadata is very accessible
* Explicit options for cloud optimised data structure including chunking of grids into tiles, compression of grids, etc.

Disadvantages:
* Relatively new and few implementations

However it may be worth consideration.

**Comment by ccrook** [comment]
@rouault, @desruisseaux Just wondering if you have any experience with or thoughts on ZARR format

**Comment by ccrook** [comment]
@palmerj FYI

**Comment by desruisseaux** [comment]
The ZARR format is evaluated in the TestBed 17 and an engineering report draft will be presented at the December OGC meeting. Even did an implementation for GDAL, he would be in best position for commenting. I did not had the chance to try it myself yet. But I got the (maybe wrong) feeling that ZARR is a format created mostly for the convenience of Python developers; it seems basically to be a Python "xarray" serialized to disk, completed with metadata as JSON files. The "cloud optimized" argument is not really convincing; chunks and data compression exist in GeoTIFF and NetCDF 4 as well. ZARR supporters said that splitting the dataset in many files is an advantage for storage such as Amazon S3. Maybe (I do not have experience with Amazon S3), but it is only one case (that argument does not hold for local file systems or storage where "HTTP range" can be used) and may be only a temporary situation while Amazon S3 system continue to improve. On the other side, I think that splitting the dataset in many files is less convenient and dangerous. Even if we can bundle all ZARR components in a single ZIP file, I think it is probable that some users will unzip the file, do some stuff with the components and recreate a ZIP file with missing or inconsistent parts.

But of course I have no objection that we try it. My impression may be wrong.

**Comment by rouault** [comment]
Whatever fits in netCDF can be done in Zarr (the nccopy utility of the netcdf-c library can convert netCDF datasets to Zarr, or the gdalmdimtranslate utility), (the main exception is that Zarr has no native concept of dimensions as in netCDF, but this is emulated in some extensions like XArray's _ARRAY_DIMENSIONS or NCZarr), so indeed no worries on the capabilities. But for an exchange format, the many file nature of Zarr would be inconvenient, and indeed zipping would be likely required. Some implementations can read directly a zipped Zarr (the GDAL one, the Python Zarr one, and I believe the netCDF-C one), but that's an extra complication for someone who would have to implement Zarr support from scratch. The many file nature of Zarr makes it convenient for scenarios where update of tile data is frequent, which is I believe secondary for GGXF purposes.  And as georeferencing is concerned, Zarr has nothing out-of-the box (Zarr doesn't come from the geospatial community). At best, it uses netCDF CF conventions for datasets originating from netCDF.

**Comment by ccrook** [comment]
@rouault @desruisseaux Thanks very much for comments.  Based on that I don't see any real advantage to using it over NetCDF.  In particular Even's comment 

>  the many file nature of Zarr would be inconvenient

is a strong argument in favour of not using Zarr - there is a very strong sentiment that at least the binary format of the GGXF  should be a single file for distribution.  

I'll leave this issue open but probably can close it off at the next GGXF meeting as not needing further consideration.

**Comment by RogerLott** [comment]
Not discussed at 2021-12-06 meeting but as @ccrook noted not needing further consideration.
