### ISSUE TITLE
NetCDF data type

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#23]
The current NetCDF implementation GGXF.py uses either float32 or float64 data types.  However it may be advantageous to use int32 or int16 data types (depending on the range for the data) using a scale factor and offset for each parameter (eg scale factor 1000 for 3dp precision and offset the median value of the parameter).  This could reduce the size of the file by half in some cases and also improve compression (not currently implemented but also an optimisation option (together with data chunking) in NetCDF.

**Comment by desruisseaux** [comment]
The [CF-conventions allow that](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#packed-data). Even if we do not generally use the CF-conventions, I think we can use the pieces that fit well and I think this is one of them. A variable stored as integers could be written like this:

```
   variables:
        short translation(j, i, axis) ;
            translation::scale_factor = 0.1;
            translation::add_offset = -0.5;
            translation::units = "mm"
```

**Comment by ccrook** [comment]
This can be invisible to users of data as mapping to floating point values is handled in NetCDF libraries.  YAML->NetCDF translator can be enhanced to either support options through command line options or "pragmas" in YAML code, or to automatically select an efficient format based on the grid data.

Closing this issue as not pertinent to current specification
