### ISSUE TITLE
Missing content type?

### ISSUE THREAD

**Issue by RogerLott** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#39]
I have been wondering whether we are missing a potentially significant content type. What about (processed) Lidar data (both DTM and DSM)? Or is that just a verticalOffset (height above national datum)? Not really, because there is no transformation and no target CRS. However it is rather analogous to a hydroid model of e.g. LAT, CD or MSL, where the tidal surface is replaced by a DTM or DSM surface. Might GGXF be used for carrying such data? Or are there already sufficient formats available for that?

**Comment by ccrook** [comment]
In my mind it is more topographic than geodetic.  However I think the main thing about LIDAR is that it has very established formats which are well integrated with the software that is used to process it and analyse it.  Ultimately it provides a digital elevation model.  So I think it is more akin to bathymetric data than tidal surfaces.  But always a question of where do we draw the line.  As an open format GGXF can hold any gridded data, geodetic or not.
