### ISSUE TITLE
Extend GGXF Conventions check point capability

### ISSUE THREAD

**Issue by RogerLott** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#64]
The checkPoints capability in r4 and earlier allows for expected results of coordinate operations to be included in the file header. By requiring sourceCrsCoordinates it precludes (without using a workaround) the inclusion of data just to check correct access to and/or interpolation of grid data, whether or not the file content supports a coordinate operation. The corrections to address this are trivial. 

Firstly, a keyword interpolationCrsCoordinates needs to be added, with definition of "Tuple of  coordinates at a check point referenced to the interpolation CRS defined in the GGXF file header. The sequence of coordinates shall be that defined for the CRS in the file header." It should be accompanied by a keyword interpolationCoordinateEpoch. (i.e. both very similar to existing definition of sourceCrsCoordinates and targetCrsCoordinates).
Secondly the definition of checkPoints needs to be amended to require either interpolationCrsCoordinates or sourceCrsCoordinates.

**Comment by RogerLott** [comment]
Updated in r5.

**Comment by ccrook** [comment]
Amended version released in [GGXF v-1-0 OGC-22-051r5_2023-10-17.pdf](https://github.com/opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format/blob/master/specification/GGXF%20v1-0%20OGC-22-051r5_2023-10-27.pdf)
