### ISSUE TITLE
Define continuity and its requirements in GGXF

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#7]
### Summary

* The GGXF implements a spatial function using one or more grids.
* Within an individual grid the function implemented by a GGXF is guaranteed to be continuous by the interpolation function.
* The function can be discontinuous at the edge of the grid.  This can be at the edge of the model or at the transition between using one grid and another if the function is defined by overlapping grids.  
* For grids which implement a transformation to or from the interpolation CRS (or a system directly related to it) then (in realistic cases) the function must be continuous to be for transformation to be invertible.
* In multiple grid solutions continuity is not generally possible unless the lattices of adjoining and overlapping grids are aligned - that is if the the grid nodes of one grid all lie on the nodes of the extension of the other grid.
* Given that the model cannot be discontinuous except at grid boundaries, which are unrelated to the physical phenomena being represented by the grid function, it is inconsistent to support discontinuities at grid boundaries.
* Missing (null) values are ignored in defining continuity.  If the model is considered undefined beyond the grids rather than 0 then the nodes at the edge of the gridded model do not need to have zero values for continuity.
* The GGXF definition could require compliant grids to be continuous, or a metadata item specifying that the grid is continuous.  

### Definition of continuity

The GGXF is used to implement a function mapping a location in the interpolation CRS to a set of values, ie:

f(x,y,...) -> (v<sub>1</sub>,v<sub>2</sub>,..)

The x,y,.. values are the ordinates in the interpolation CRS, most typically longitude, latitude, or easting, northing in a projected coordinate system. However we may include additional ordinates, for example height or time. 

The calculated values v<sub>1</sub>,v<sub>2</sub>,.. depend on the purpose of the function.  For example in a geoid model there might be just one value, geoid height.  The model might also include a value for representing the uncertainty of the geoid height.  

A common expectation of the function f is that it is continuous (see for example [Wikipedia](https://en.wikipedia.org/wiki/Continuous_function)). Mathematically the function f is continuous at a point x<sub>0</sub>, y<sub>0</sub> if for any arbitrarily small value &delta;v > 0 there exists a value &delta; > 0 such that

|f(x,y)-f(x<sub>0</sub>,y<sub>0</sub>)| <  &delta;v 

for all x in the range [x<sub>0</sub>-&delta;,x<sub>0</sub>+&delta;] and for all y in the range [y<sub>0</sub>-&delta;,y<sub>0</sub>+&delta;].  In this formula the expression |..| is a measure of the difference in the function evaluated at x,y and at x<sub>0</sub>,y<sub>0</sub>.  For example it could be the maximum of the difference in the v1, v2 .. values at the two points.

This formula expresses the intuitive idea of continuity - if the function is visualised as a surface then there are no steps in the surface.   

> image to be inserted

Computers have finite precision of arithmetic, so in a computational environment this could be replaced with:

|f(x,y)-f(x<sub>0</sub>,y<sub>0</sub>)| <  &delta;v + &epsilon;

where &epsilon; is a measure of the numerical precision of the computation.  

Also where the values v<sub>1</sub>, v<sub>2</sub> represent a measured or estimated physical quantity we may choose to relax the continuity requirement by allowing a discontinuity of up to &sigma; which is related in a defined way to the uncertainty of the estimate, ie

|f(x,y)-f(x<sub>0</sub>,y<sub>0</sub>)| <  &delta;v + &epsilon; + &sigma;

### Continuity of a GGXF function

In a gridded data set the spatial function f is implemented by defining the values v1<sub>i,j</sub> v2<sub>i,j</sub> at the nodes x<sub>i,j</sub>, y<sub>i,j</sub> of the grid for the grid columns i and rows j. Associated with the grid as an interpolation function (eg bilinear) that is used to calculate the values for any other location x,y within the extent of the grid.

The interpolation function guarantees that the this function is continuous across the extent of the grid. The interpolation function is continuous across each grid cell, and continuity at the edges where grid cells meet is guaranteed because the interpolated value at the edge depends only on the shared values along that edge (or in the case of bicubic interpolation, on the extension of the that common edge).

However the function may be discontinuous at the edge of the grid if the extent of the model is greater than that of the grid. In that case the function will be evaluated as zero outside the extent of the grid.  To ensure the function is continuous, the values v1,v2 at the edges of the grid must also evaluate to zero.  

The situation is more complex where the function is represented by multiple overlapping or touching grids and where the evaluation at each point is done by choosing just one grid and evaluating the function using that.  This is commonly the case in nested grid structures (for example NTv2 distortion grids).  If the function is to be continuous then at the transition between two grids the values calculated on each grid must be the same. 

In this case a requirement for continuity creates constraints on the construction of the grids and on the values at the grid nodes.

The constraint on construction is that adjacent grids are aligned.   For every edge where the model transitions from one grid to another the grid nodes of one grid must all lie on the nodes of the extension of the other grid. This requirement is because an interpolation function in one grid cell or edge can exactly match an interpolation in an overlapping cell or edge, but generally it cannot match two different interpolation functions.

In theory this need not be true if function value along the common edge is constant or if one grid lies entirely within a single grid cell of the other, but these are very artificial and impractical scenarios.

This is illustrated below for the case of bilinear interpolation at an edge where two grids meet.

> image to be inserted

The constraint on grid values is that at each edge where the function transitions from one using grid to using another the values interpolated for each grid must be the same.  

If continuity is required it is the grid producers responsibility to ensure these conditions are met (though they can be tested by validation tools).

### Invertibility of a GGXF based transformation function

The primary use case for GGXF grids is to support coordinate system operations.  This includes transforming between vertical datums, converting between distorted historic two dimensional datums and more recent and accurate datums, and applying time based transformations to account for deformation.

We generally require these transformations to be invertible.  That is, the transformation grid that is used to convert coordinates from datum A to datum B can also be used to convert coordinates from datum B to datum A.  The transformation should calculate a unique coordinate in datum B for each coordinate in datum A that is within the extents of the grid, and vice versa.

For vertical transformations this is always the case.  The GGXF is used to calculate the height different between datum B and datum A at a horizontal location.  This is added to the height to transform from A to B, and subtracted to transform from B to A.  (In fact this could be untrue if the interpolation coordinate system includes a height coordinate but this is not the case for any height transformations currently in use)

For transformations involving horizontal locations this is more complex.  Evaluating the transformation requires a coordinate in the interpolation CRS, and for the inverse transformation the coordinate in the interpolation CRS is not known until the transformation has been applied. 

If the transformation function is discontinuous then there may be no unique solution for the inverse transformation.  

Mathematically continuity of the gridded function f and invertibility of the transformation function it implements are independent requirement.  A function can be invertible, but not continuous, or continuous but not invertible.  However for all realistic transformation cases the two requirements are the same - if the function is continuous it will be invertible, and if it is discontinuous it will not be invertible.  

### Continuity and null values 

If the model supports null or missing values either within the grid or beyond the edge of the grid then the continuity requirement only applies between non null values.  The formula

|f(x,y)-f(x<sub>0</sub>,y<sub>0</sub>)| <  &delta;v 

the value |f(x,y)-f(x<sub>0</sub>,y<sub>0</sub>)| can be treated as evaluating to 0 if f(x,y) or f(x<sub>0</sub>,y<sub>0</sub>) is a null value.

In particular if the model is considered to be null outside its defined extent then the edge values do not have to be 0 to ensure continuity.

**Comment by ccrook** [comment]
Arguably GGXF shouldn't specify continuity - that is in the domain of the application using GGXF rather than GGXF itself.  Also it is at the producers discretion.   We could develop a GGXF checking utility which tests continuity of the GGXF group data.  A software implementation will need to have some sort of exception handling to deal with a poorly constructed GGXF in any case, so adding the specification doesn't necessarily simplify software.  The most likely impact of software is non-invertibility of transformations where the interpolation CRS is the same as (or a 2d version of) the source or target CRS.

Currently I think there is only one brief comment on continuity in the specification which is in 6.3.2:

> To ensure continuity across the boundary of child grids, in grid creation the
parameter values at nodes on the boundary of a child grid must be derivable
through interpolation of its parent grid, but parameter values at interior nodes of
the child grid are not constrained by the parent grid.

Technically this is not correct where two child grids abut as they only need to match each other at their common edge, they don't need to match the parent grid. 

Completely specifying conditions for continuity is complex - I suggest that this is  not included in the normative section of the document.  Instead maybe there can be an informative recommendation.

@RogerLott - I haven't closed this because of the comment re section 6.3.2 for your attention, but happy for you to close it.

**Comment by RogerLott** [comment]
Does this overlap with issue #21?

**Comment by RogerLott** [comment]
I suggest we include this in Wednesday's discussion.

**Comment by ccrook** [comment]
With regard to #21 I think this does not directly overlap.  Issue #21 is a question about bicubic/biquadratic interpolation formulae at the edge of a single grid which is different to continuity at transitions between grids.

**Comment by ccrook** [comment]
The specification embodies this as a recommendation in section 6.3.2 "Continuity across multiple grids" (version 0.95 spec) .  This issue can now be closed
