### ISSUE TITLE
Clarification on "grid to CRS" matrix

### ISSUE THREAD

**Issue by desruisseaux** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#8]
# Clarification on "grid to CRS" matrix

This is an attempt to clarify how to use the "grid to CRS" matrix described in the _"Conversion from CRS coordinates to grid coordinates"_ section of issue #6. We need to handle all the cases illustrated below (figure provided by Roger):

![image](https://user-images.githubusercontent.com/1324414/107378195-042fce00-6aec-11eb-82b2-7107de136c2a.png)

The conversion can be represented in matrix form as below. This equation uses the same symbols than EPSG _"Affine parametric transformation"_ operation method (EPSG::9624). (X<sub>S</sub>,Y<sub>S</sub>) are source coordinates and (X<sub>T</sub>,Y<sub>T</sub>) are target coordinates. In the context of GGXF, source coordinate are grid indices (we will call them _i_,_j_ later) and target coordinates are geodetic or projected coordinates.

![image](https://user-images.githubusercontent.com/1324414/107378670-80c2ac80-6aec-11eb-8b4f-184e73463bf5.png)

The translation matrix (with A<sub>0</sub> and B<sub>0</sub> terms) can be combined with the scale matrix (with A<sub>1</sub>, A<sub>2</sub>, B<sub>1</sub> and B<sub>2</sub> terms) into a single matrix by using a mathematical trick: in all matrices, a row is added with 0 values everywhere except in the last column where the value is 1. Because the last row of the combined matrix is always exactly as described (in the affine transform case; it could be different in _perspective transform_ case but the later is out of scope), that row is omitted in file formats such as _"World File"_ TFW files. But we write those rows anyway in this discussion in order to show mathematically correct matrix operations.

![image](https://user-images.githubusercontent.com/1324414/107378992-ce3f1980-6aec-11eb-9827-14fe49dcabb5.png)

The use of a combined matrix as shown above is convenient because the inverse of this matrix (the "CRS to grid" conversion) has the same form. If there is many affine transforms to concatenate, their matrices can be multiplied and the result still have the same form. The proposal is to use that combined matrix form for representing all needed conversions as below. In the following matrices, source coordinates (X<sub>S</sub>,Y<sub>S</sub>) are replaced by grid indices (_i_,_j_) and target coordinates (X<sub>T</sub>,Y<sub>T</sub>) are replaced by easting (E), northing (N), westing (W) or southing (S) depending on the sign of matrix terms.

![image](https://user-images.githubusercontent.com/1324414/107379475-3f7ecc80-6aed-11eb-9c2d-6638cf12b130.png)

**Observations** (ignoring the last matrix row for all items below):
* The order of terms in the leftmost matrix ([E N], [N W], _etc._) must match coordinate order of interpolation CRS.
* The order of terms in the rightmost matrix must match grid coordinate order. In this discussion that order is fixed to (_i_,_j_) for all cases, regardless interpolation CRS axis order.
* The middle matrix always have two terms equal to zero. It will always be the case for all combinations of scale, translation, flip and quadrant rotations (i.e. rotation by a multiple of 90°). However the locations of zero terms in the matrix vary depending on interpolation CRS axis order.

The GGFX format should declare the 6 terms of the middle matrix, ignoring last row. Because 2 of those terms are always equal to zero (if there is no shear and rotation by a non-multiple of 90°), it is tempting to declare only the 4 non-zero terms, especially since those 4 terms can be mapped to a bounding box, which is more intuitive than an affine transform. However even if the zero values seem useless, their position in the matrix do convey an information about axis order. Dropping those 2 values causes the replacement of explicit axis order information by some implicit assumptions, therefore bringing the ambiguity that caused so much harm in the last decades.

## Possible constraint
In order to keep the matrix simple, the specification could put the following constraint:

> Each row in the matrix can have at most one non-zero term in addition of the translation term (translation terms are the values in the last column).

Taking the notation at the beginning of this discussion, it means that one of the following conditions must be true:

* A<sub>2</sub>=0 and B<sub>1</sub>=0 (conversion with no axis swapping)
* A<sub>1</sub>=0 and B<sub>2</sub>=0 (conversion with axis swapping)

The effect of this restriction is to forbid shears and rotations by any angle that is not a multiple of 90°. If a future version or a profile of GGXF format allows arbitrary rotations, there is no need for any change in the specification other than dropping above constraint.

## Generalization to _n_ dimensions
Above discussion was for a two-dimensional conversion. But it can easily be generalized to three or more dimensions. We only need to add one row and one column in the combined matrix for each additional dimension.

**Comment by ccrook** [comment]
Implemented in GGXF specification so closing this issue.  Added a link in on the [wiki home page](https://github.com/opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format/wiki/Home) to keep this content visible as it is a very valuable reference.
